#!/bin/bash
#PBS -q checkpt
#PBS -A hpc_houmicro06
#PBS -l nodes=1:ppn=20
#PBS -l walltime=0:10:00
#PBS -o /work/bmath27/sterivex/
#PBS -j oe
#PBS -N diversity.diversion
#PBS -m abe
#PBS -M bmath27@lsu.edu
date

cd /work/bmath27/
unset PYTHONPATH
unset PYTHONUSERBASE
source activate qiime2-2021.11
cd /work/bmath27/sterivex/

# Must first filter samples and make a new table file based on desired samples

qiime feature-table filter-samples \
  --i-table data/qiime/table.qza \
  --m-metadata-file data/references/diversion.flow.metadata.tsv \
  --o-filtered-table data/qiime/diversion-table.qza


# Alpha and Beta Diversity Analysis
    #Sampling depth set at minimum frequency to preserve all samples
qiime diversity core-metrics-phylogenetic \
    --i-phylogeny data/qiime/rooted-tree.qza \
    --i-table data/qiime/diversion-table.qza \
    --p-sampling-depth 5906 \
    --m-metadata-file data/references/diversion.flow.metadata.tsv \
    --output-dir data/process/core-metrics-results/diversion

qiime diversity alpha-group-significance \
        --i-alpha-diversity data/process/core-metrics-results/diversion/evenness_vector.qza \
        --m-metadata-file data/references/diversion.metadata.tsv \
        --o-visualization data/process/core-metrics-results/diversion/evenness-group-significance.qzv

qiime diversity alpha-group-significance \
        --i-alpha-diversity data/process/core-metrics-results/diversion/faith_pd_vector.qza \
        --m-metadata-file data/references/diversion.metadata.tsv \
        --o-visualization data/process/core-metrics-results/diversion/faith-pd-group-significance.qzv

qiime diversity beta-group-significance \
	  --i-distance-matrix data/process/core-metrics-results/diversion/unweighted_unifrac_distance_matrix.qza \
          --m-metadata-file data/references/diversion.metadata.tsv \
          --m-metadata-column Location \
          --o-visualization data/process/core-metrics-results/diversion/unweighted-unifrac-station-significance-location.qzv \
          --p-pairwise

qiime diversity beta-group-significance \
          --i-distance-matrix data/process/core-metrics-results/diversion/unweighted_unifrac_distance_matrix.qza \
          --m-metadata-file data/references/diversion.metadata.tsv \
          --m-metadata-column Time \
          --o-visualization data/process/core-metrics-results/diversion/unweighted-unifrac-station-significance-time.qzv \
          --p-pairwise

qiime diversity beta-group-significance \
          --i-distance-matrix data/process/core-metrics-results/diversion/unweighted_unifrac_distance_matrix.qza \
          --m-metadata-file data/references/diversion.metadata.tsv \
          --m-metadata-column studyid \
          --o-visualization data/process/core-metrics-results/diversion/unweighted-unifrac-station-significance-study.qzv \
          --p-pairwise

qiime diversity beta-group-significance \
          --i-distance-matrix data/process/core-metrics-results/diversion/unweighted_unifrac_distance_matrix.qza \
          --m-metadata-file data/references/diversion.metadata.tsv \
          --m-metadata-column Description \
          --o-visualization data/process/core-metrics-results/diversion/unweighted-unifrac-station-significance-description.qzv \
          --p-pairwise

# Ordination by salinity
qiime emperor plot \
  --i-pcoa data/process/core-metrics-results/diversion/unweighted_unifrac_pcoa_results.qza \
  --m-metadata-file data/references/diversion.metadata.tsv \
  --p-custom-axes Salinity \
  --o-visualization data/process/core-metrics-results/diversion/unweighted-unifrac-emperor-salinity.qzv

qiime emperor plot \
  --i-pcoa data/process/core-metrics-results/diversion/bray_curtis_pcoa_results.qza \
  --m-metadata-file data/references/diversion.metadata.tsv \
  --p-custom-axes Salinity \
  --o-visualization data/process/core-metrics-results/diversion/bray-curtis-emperor-salinity.qzv

#Alpha Rarefaction Plotting
	# * Choose max depth based on median frequency per sample value in table.qzv file
  #Chose based on median frequency of all sterivex data
qiime diversity alpha-rarefaction \
  --i-table data/qiime/table.qza \
  --i-phylogeny data/qiime/rooted-tree.qza \
  --p-max-depth 18609 \
  --m-metadata-file data/references/diversion.metadata.tsv \
  --o-visualization data/process/alpha-rarefaction-diversion.qzv

date
exit 0
