#!/bin/bash
#PBS -q workq
#PBS -A hpc_houmicro06
#PBS -l nodes=1:ppn=28
#PBS -l walltime=2:00:00
#PBS -o /work/bmath27/breton.sound.sterivex/
#PBS -j oe
#PBS -N trainset
#PBS -m abe
#PBS -M bmath27@lsu.edu
date

cd /work/bmath27/
unset PYTHONPATH
unset PYTHONUSERBASE
source activate qiime2-2021.11
cd /work/bmath27/breton.sound.sterivex




qiime taxa filter-table \
  --i-table table.qza \
  --i-taxonomy taxonomy.qza \
  --p-exclude mitochondria,chloroplast \
  --o-filtered-table table-no-mitochondria-no-chloroplast.qza

  date
  exit 0
